name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 16.17.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.0
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm -r install --frozen-lockfile
        working-directory: .

      - name: npm install and build
        run: pnpm run build
